# =================================
# pipeline configs
# =================================

pipeline = "baseline.pipelines.snerf.SNerfPipeline"
precision = 32  # precision of the pipeline (16 for half prec, 32 for normal float32)
use_utm_coordinate_system  = false  # wether to use UTM or ECEF coordinate system
version = 1

# =================================
# model parameters
# =================================
n_samples = 64  # number of coarse scale discrete points per input ray
use_fine_network = false  # should a separate fine network be used
n_importance = 0  # number of fine scale discrete points per input ray
render_chunk_size = 5120 # how many points are evaulated at the same time (5120, 10240, 40960, ...)
batch_size = 1024  # how many views are handled at the same time (old value = 1024)
learnrate = 5e-4 # initial learnrate
noise_std = 0.0  # standard deviation of noise added to sigma to regularize
fc_units = 512  # number of units in fully-connected network
fc_layers = 8  # number of layers in fully-connected network
fc_skips = [4]

# =================================
# shadow nerf
# =================================
sc_lambda = 0.05  # multiplicator for solar correction auxiliary loss
